---
ID: "1408eb2c-1567-4fbd-b5ff-c3141a8590b5"
Parent: "ab622812-898f-4146-a35b-040f9ff7645a"
Template: "ab622812-898f-4146-a35b-040f9ff7645a"
Path: /sitecore/templates/GeTask/Feature/MyPosts/Table Info/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190716T134008Z
    - ID: "4e0e4b8c-4e67-4041-a948-18591c97a48e"
      Hint: UserId
      Value: UserId
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "9b5cae54-fb5f-4845-b571-2e887d15e62b"
      Hint: ItemsCount
      Value: 3
    - ID: "d01a8e53-4ab2-40b2-a32f-7ca307e8a26e"
      Hint: Description
      Value: Description
    - ID: "e3f74a33-3f0e-43ed-a2e6-78e3cb9cad17"
      Hint: Title
      Value: Title
